### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by amcsi** [papnkukn/qrcode-svg#4] opened 2018-06-22 19:38 UTC
When requiring this library for browser frontend use, I get this error.

Everything works otherwise, it's just this error showing in the console is annoying.

**Comment by Ridermansb** [comment] 2018-11-02 17:09
Same for me, using preact-cli

**Comment by agrohs** [comment] 2018-12-11 16:56
same here using straight node

**Comment by agrohs** [comment] 2018-12-11 17:11
appears that by adding the following export into my webpack config that the library works:

    node: {
        fs: 'empty'
    },

**Comment by khaukheng** [comment] 2019-10-25 08:41
Same here in Angular project, it prevents compilation too.

**Comment by papnkukn** [comment] 2019-10-29 18:56
The issue has been with the function `save` which works fine in node.js environment. However, a web browser does not have an open access to the file system, thus resulting in an error (`require('fs')`)

Hope the issue has been resolved with the version 1.1.0. Invoking the `save(...)` in a web browser will kindly pass the error in a callback function.

**Closed by papnkukn** 2019-10-29 18:56 UTC

**Comment by khaukheng** [comment] 2019-11-01 04:17
> The issue has been with the function `save` which works fine in node.js environment. However, a web browser does not have an open access to the file system, thus resulting in an error (`require('fs')`)
> 
> Hope the issue has been resolved with the version 1.1.0. Invoking the `save(...)` in a web browser will kindly pass the error in a callback function.

Hi, do you mean we cannot use this library with frontend code?
But it is working fine in this example https://codepen.io/bocko/pen/YLWNgj

**Comment by papnkukn** [comment] 2019-11-12 16:37
Yes, the library works fine within the browser (frontend) - the algorithm is pure JavaScript after all.

Just to make it clear - only the `save` function is not available in the browser.

**Comment by vision10** [comment] 2022-02-23 11:09
The problem is still there for angular projects. It does build but with a warning
/node_modules/qrcode-svg/lib/qrcode.js:413:13-26 - Warning: Module not found: Error: Can't resolve 'fs' in '...\node_modules\qrcode-svg\lib' 

Why do we even need this save function that writes just the qrcode to a file?
Most of the time I just need the qrcode to insert it in a document, maybe save in a database, and send it to the printer.

**Comment by arthurshlain** [comment] 2024-08-20 09:44
For laravel-mix:

```js
// webpack.mix.js

mix.webpackConfig({
    resolve: {
        fallback: {
            fs: false
        }
    }
});
```
